/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsDatabaseRouteImport } from './routes/settings/database'
import { Route as SettingsCommonRouteImport } from './routes/settings/common'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SettingsProviderRouteRouteImport } from './routes/settings/provider/route'
import { Route as SettingsProviderIndexRouteImport } from './routes/settings/provider/index'
import { Route as SettingsProviderProviderIdRouteImport } from './routes/settings/provider/$providerId'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDatabaseRoute = SettingsDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCommonRoute = SettingsCommonRouteImport.update({
  id: '/common',
  path: '/common',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProviderRouteRoute = SettingsProviderRouteRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProviderIndexRoute = SettingsProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsProviderRouteRoute,
} as any)
const SettingsProviderProviderIdRoute =
  SettingsProviderProviderIdRouteImport.update({
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => SettingsProviderRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/provider': typeof SettingsProviderRouteRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/common': typeof SettingsCommonRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider/': typeof SettingsProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/common': typeof SettingsCommonRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider': typeof SettingsProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/provider': typeof SettingsProviderRouteRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/common': typeof SettingsCommonRoute
  '/settings/database': typeof SettingsDatabaseRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider/': typeof SettingsProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/provider'
    | '/settings/account'
    | '/settings/common'
    | '/settings/database'
    | '/chat/'
    | '/settings/'
    | '/settings/provider/$providerId'
    | '/settings/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/account'
    | '/settings/common'
    | '/settings/database'
    | '/chat'
    | '/settings'
    | '/settings/provider/$providerId'
    | '/settings/provider'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/provider'
    | '/settings/account'
    | '/settings/common'
    | '/settings/database'
    | '/chat/'
    | '/settings/'
    | '/settings/provider/$providerId'
    | '/settings/provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/database': {
      id: '/settings/database'
      path: '/database'
      fullPath: '/settings/database'
      preLoaderRoute: typeof SettingsDatabaseRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/common': {
      id: '/settings/common'
      path: '/common'
      fullPath: '/settings/common'
      preLoaderRoute: typeof SettingsCommonRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/provider/': {
      id: '/settings/provider/'
      path: '/'
      fullPath: '/settings/provider/'
      preLoaderRoute: typeof SettingsProviderIndexRouteImport
      parentRoute: typeof SettingsProviderRouteRoute
    }
    '/settings/provider/$providerId': {
      id: '/settings/provider/$providerId'
      path: '/$providerId'
      fullPath: '/settings/provider/$providerId'
      preLoaderRoute: typeof SettingsProviderProviderIdRouteImport
      parentRoute: typeof SettingsProviderRouteRoute
    }
  }
}

interface SettingsProviderRouteRouteChildren {
  SettingsProviderProviderIdRoute: typeof SettingsProviderProviderIdRoute
  SettingsProviderIndexRoute: typeof SettingsProviderIndexRoute
}

const SettingsProviderRouteRouteChildren: SettingsProviderRouteRouteChildren = {
  SettingsProviderProviderIdRoute: SettingsProviderProviderIdRoute,
  SettingsProviderIndexRoute: SettingsProviderIndexRoute,
}

const SettingsProviderRouteRouteWithChildren =
  SettingsProviderRouteRoute._addFileChildren(
    SettingsProviderRouteRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingsProviderRouteRoute: typeof SettingsProviderRouteRouteWithChildren
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsCommonRoute: typeof SettingsCommonRoute
  SettingsDatabaseRoute: typeof SettingsDatabaseRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProviderRouteRoute: SettingsProviderRouteRouteWithChildren,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsCommonRoute: SettingsCommonRoute,
  SettingsDatabaseRoute: SettingsDatabaseRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
