/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VideoIndexRouteImport } from './routes/video/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as SettingsUsageRouteImport } from './routes/settings/usage'
import { Route as SettingsSubscriptionRouteImport } from './routes/settings/subscription'
import { Route as SettingsOrdersRouteImport } from './routes/settings/orders'
import { Route as SettingsCommonRouteImport } from './routes/settings/common'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as SettingsSubscriptionCheckoutRouteImport } from './routes/settings/subscription/checkout'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoIndexRoute = VideoIndexRouteImport.update({
  id: '/video/',
  path: '/video/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSubscriptionRoute = SettingsSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsOrdersRoute = SettingsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCommonRoute = SettingsCommonRouteImport.update({
  id: '/common',
  path: '/common',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSubscriptionCheckoutRoute =
  SettingsSubscriptionCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => SettingsSubscriptionRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/common': typeof SettingsCommonRoute
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/subscription': typeof SettingsSubscriptionRouteWithChildren
  '/settings/usage': typeof SettingsUsageRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/video/': typeof VideoIndexRoute
  '/settings/subscription/checkout': typeof SettingsSubscriptionCheckoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/common': typeof SettingsCommonRoute
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/subscription': typeof SettingsSubscriptionRouteWithChildren
  '/settings/usage': typeof SettingsUsageRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/video': typeof VideoIndexRoute
  '/settings/subscription/checkout': typeof SettingsSubscriptionCheckoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/settings/account': typeof SettingsAccountRoute
  '/settings/common': typeof SettingsCommonRoute
  '/settings/orders': typeof SettingsOrdersRoute
  '/settings/subscription': typeof SettingsSubscriptionRouteWithChildren
  '/settings/usage': typeof SettingsUsageRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/video/': typeof VideoIndexRoute
  '/settings/subscription/checkout': typeof SettingsSubscriptionCheckoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/settings/account'
    | '/settings/common'
    | '/settings/orders'
    | '/settings/subscription'
    | '/settings/usage'
    | '/chat/'
    | '/settings/'
    | '/video/'
    | '/settings/subscription/checkout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/account'
    | '/settings/common'
    | '/settings/orders'
    | '/settings/subscription'
    | '/settings/usage'
    | '/chat'
    | '/settings'
    | '/video'
    | '/settings/subscription/checkout'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/settings/account'
    | '/settings/common'
    | '/settings/orders'
    | '/settings/subscription'
    | '/settings/usage'
    | '/chat/'
    | '/settings/'
    | '/video/'
    | '/settings/subscription/checkout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
  VideoIndexRoute: typeof VideoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video/': {
      id: '/video/'
      path: '/video'
      fullPath: '/video/'
      preLoaderRoute: typeof VideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/subscription': {
      id: '/settings/subscription'
      path: '/subscription'
      fullPath: '/settings/subscription'
      preLoaderRoute: typeof SettingsSubscriptionRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/orders': {
      id: '/settings/orders'
      path: '/orders'
      fullPath: '/settings/orders'
      preLoaderRoute: typeof SettingsOrdersRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/common': {
      id: '/settings/common'
      path: '/common'
      fullPath: '/settings/common'
      preLoaderRoute: typeof SettingsCommonRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/subscription/checkout': {
      id: '/settings/subscription/checkout'
      path: '/checkout'
      fullPath: '/settings/subscription/checkout'
      preLoaderRoute: typeof SettingsSubscriptionCheckoutRouteImport
      parentRoute: typeof SettingsSubscriptionRoute
    }
  }
}

interface SettingsSubscriptionRouteChildren {
  SettingsSubscriptionCheckoutRoute: typeof SettingsSubscriptionCheckoutRoute
}

const SettingsSubscriptionRouteChildren: SettingsSubscriptionRouteChildren = {
  SettingsSubscriptionCheckoutRoute: SettingsSubscriptionCheckoutRoute,
}

const SettingsSubscriptionRouteWithChildren =
  SettingsSubscriptionRoute._addFileChildren(SettingsSubscriptionRouteChildren)

interface SettingsRouteRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsCommonRoute: typeof SettingsCommonRoute
  SettingsOrdersRoute: typeof SettingsOrdersRoute
  SettingsSubscriptionRoute: typeof SettingsSubscriptionRouteWithChildren
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsCommonRoute: SettingsCommonRoute,
  SettingsOrdersRoute: SettingsOrdersRoute,
  SettingsSubscriptionRoute: SettingsSubscriptionRouteWithChildren,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
  VideoIndexRoute: VideoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
